name: ssWWWZjj
channels:
  - conda-forge
dependencies:
  - python=3.10
  - uproot
  - numpy
  - pandas
  - matplotlib
  - root
  - mplhep
  - ca-certificates
  - openssl
  - joblib
  - certifi
  - scikit-learn
  - optuna
  - ipywidgets
  - jupyterlab
